/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.main;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

/**
 *
 * @author binta
 */
public class Sampah_tambah extends javax.swing.JDialog {

    /**
     * Creates new form Sampah_tambah
     */
    public Sampah_tambah(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kodesampah_tambah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_kategori_tmbhsampah = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_jenissampah_tambah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_deskripsi_tambah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_hargadhs1_tambah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_hargadhs2_tambah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_hargapgpl_tambah = new javax.swing.JTextField();
        btn_ttpTambahsampah = new javax.swing.JButton();
        btn_simpahDataSampah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(324, 538));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 112, 192));
        jPanel2.setPreferredSize(new java.awt.Dimension(243, 42));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAMBAH DATA SAMPAH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Kode Sampah");

        txt_kodesampah_tambah.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Kategori");

        cmb_kategori_tmbhsampah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Organik", "Anorganik", " " }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Jenis Sampah");

        txt_jenissampah_tambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jenissampah_tambahKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Deskripsi");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Harga Dhs 1");

        txt_hargadhs1_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargadhs1_tambahActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Harga Dhs 2");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Harga ke Pengepul");

        btn_ttpTambahsampah.setBackground(new java.awt.Color(255, 51, 0));
        btn_ttpTambahsampah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_ttpTambahsampah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ttpTambahsampah.setText("Tutup");
        btn_ttpTambahsampah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ttpTambahsampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttpTambahsampahActionPerformed(evt);
            }
        });

        btn_simpahDataSampah.setBackground(new java.awt.Color(0, 112, 192));
        btn_simpahDataSampah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_simpahDataSampah.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpahDataSampah.setText("Simpan");
        btn_simpahDataSampah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_simpahDataSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpahDataSampahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ttpTambahsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btn_simpahDataSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(txt_kodesampah_tambah)
                    .addComponent(jLabel3)
                    .addComponent(cmb_kategori_tmbhsampah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(txt_jenissampah_tambah)
                    .addComponent(jLabel5)
                    .addComponent(txt_deskripsi_tambah)
                    .addComponent(jLabel6)
                    .addComponent(txt_hargadhs1_tambah)
                    .addComponent(jLabel7)
                    .addComponent(txt_hargadhs2_tambah)
                    .addComponent(jLabel8)
                    .addComponent(txt_hargapgpl_tambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kodesampah_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_kategori_tmbhsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_jenissampah_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_deskripsi_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hargadhs1_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hargadhs2_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hargapgpl_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ttpTambahsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpahDataSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hargadhs1_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargadhs1_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargadhs1_tambahActionPerformed

    private void btn_simpahDataSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpahDataSampahActionPerformed

        String kategori = cmb_kategori_tmbhsampah.getSelectedItem().toString();
        String jenis = txt_jenissampah_tambah.getText();
        String deskripsi = txt_deskripsi_tambah.getText();
        String harga1Text = txt_hargadhs1_tambah.getText();
        String harga2Text = txt_hargadhs2_tambah.getText();
        String hargaPengepulText = txt_hargapgpl_tambah.getText();

        if (kategori.isEmpty() || jenis.isEmpty() || deskripsi.isEmpty()
                || harga1Text.isEmpty() || harga2Text.isEmpty() || hargaPengepulText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        try {
            double harga1 = Double.parseDouble(harga1Text);
            double harga2 = Double.parseDouble(harga2Text);
            double hargaPengepul = Double.parseDouble(hargaPengepulText);

            String kode = SampahUtil.generateKodeSampah(jenis); 
            txt_kodesampah_tambah.setText(kode); 

            try (Connection conn = com.koneksi.koneksi.konek()) {
                String sql = "INSERT INTO sampah (kode_sampah, kategori, jenis, deskripsi, harga1, harga2, harga_pengepul, stok, created_at, updated_at) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, 0, NOW(), NOW())";

                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, kode);
                pst.setString(2, kategori);
                pst.setString(3, jenis);
                pst.setString(4, deskripsi);
                pst.setDouble(5, harga1);
                pst.setDouble(6, harga2);
                pst.setDouble(7, hargaPengepul);

                int rows = pst.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Data sampah berhasil disimpan!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan data.");
                }

                pst.close();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage());
        }

    }//GEN-LAST:event_btn_simpahDataSampahActionPerformed

    private void btn_ttpTambahsampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttpTambahsampahActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_ttpTambahsampahActionPerformed

    private void txt_jenissampah_tambahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jenissampah_tambahKeyReleased
        String jenis = txt_jenissampah_tambah.getText().trim();
        if (!jenis.isEmpty()) {
            String kode = SampahUtil.generateKodeSampah(jenis);
            txt_kodesampah_tambah.setText(kode);
        }
    }//GEN-LAST:event_txt_jenissampah_tambahKeyReleased

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sampah_tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sampah_tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sampah_tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sampah_tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sampah_tambah dialog = new Sampah_tambah(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpahDataSampah;
    private javax.swing.JButton btn_ttpTambahsampah;
    private javax.swing.JComboBox<String> cmb_kategori_tmbhsampah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_deskripsi_tambah;
    private javax.swing.JTextField txt_hargadhs1_tambah;
    private javax.swing.JTextField txt_hargadhs2_tambah;
    private javax.swing.JTextField txt_hargapgpl_tambah;
    private javax.swing.JTextField txt_jenissampah_tambah;
    private javax.swing.JTextField txt_kodesampah_tambah;
    // End of variables declaration//GEN-END:variables

    public class SampahUtil {

        public static String generateKodeSampah(String jenis) {
            String prefix = getPrefixByJenis(jenis); // otomatis ambil 3 huruf pertama
            String kodeBaru = "";
            int nomorBaru = 1;

            try (Connection conn = com.koneksi.koneksi.konek()) {
                String sql = "SELECT kode_sampah FROM sampah WHERE kode_sampah LIKE ? ORDER BY kode_sampah DESC LIMIT 1";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, prefix + "%");
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String lastKode = rs.getString("kode_sampah");
                    String angka = lastKode.substring(3);  
                    nomorBaru = Integer.parseInt(angka) + 1;
                }

                rs.close();
                pst.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal generate kode: " + e.getMessage());
            }

            kodeBaru = String.format("%s%05d", prefix, nomorBaru); // contoh: KER00001
            return kodeBaru;
        }

        private static String getPrefixByJenis(String jenis) {
            jenis = jenis.trim().toUpperCase();

            if (jenis.length() >= 3) {
                return jenis.substring(0, 3);
            } else {
                return String.format("%-3s", jenis).replace(' ', 'X'); // isi X jika kurang dari 3 huruf
            }
        }
    }

}
