/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.main;

import java.awt.Frame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;

/**
 *
 * @author binta
 */
public class Sampah_edit extends javax.swing.JDialog {

    private String kodeSampah;

    /**
     * Creates new form Sampah_edit
     */
    public Sampah_edit(java.awt.Frame parent, boolean modal, String kodeSampah) {
        super(parent, modal);
        this.kodeSampah = kodeSampah;
        initComponents();
        loadFormEditSampah(kodeSampah);
    }
    
    private Sampah_edit(JFrame jFrame, boolean b) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kodesampah_tambah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_kategori_edtsampah = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_jenissampah_edt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_deskripsi_edt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_hargadhs1_edt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_hargadhs2_edt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_hargapgpl_edt = new javax.swing.JTextField();
        btn_ttpEditsampah = new javax.swing.JButton();
        btn_simpahEditSampah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(324, 538));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EDIT DATA SAMPAH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Kode Sampah");

        txt_kodesampah_tambah.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Kategori");

        cmb_kategori_edtsampah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Organik ", "Anorganik" }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Jenis Sampah");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Deskripsi");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Harga Dhs 1");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Harga Dhs 2");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Harga ke Pengepul");

        btn_ttpEditsampah.setBackground(new java.awt.Color(255, 51, 0));
        btn_ttpEditsampah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_ttpEditsampah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ttpEditsampah.setText("Tutup");
        btn_ttpEditsampah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ttpEditsampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttpEditsampahActionPerformed(evt);
            }
        });

        btn_simpahEditSampah.setBackground(new java.awt.Color(0, 112, 192));
        btn_simpahEditSampah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_simpahEditSampah.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpahEditSampah.setText("Simpan");
        btn_simpahEditSampah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_simpahEditSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpahEditSampahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ttpEditsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btn_simpahEditSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_kodesampah_tambah)
                        .addComponent(jLabel2)
                        .addComponent(cmb_kategori_edtsampah, 0, 300, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(txt_jenissampah_edt)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(txt_deskripsi_edt)
                        .addComponent(txt_hargadhs1_edt)
                        .addComponent(jLabel6)
                        .addComponent(txt_hargadhs2_edt)
                        .addComponent(jLabel7)
                        .addComponent(txt_hargapgpl_edt)
                        .addComponent(jLabel8)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kodesampah_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_kategori_edtsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_jenissampah_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_deskripsi_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hargadhs1_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hargadhs2_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hargapgpl_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ttpEditsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpahEditSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ttpEditsampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttpEditsampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ttpEditsampahActionPerformed

    private void btn_simpahEditSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpahEditSampahActionPerformed
        String kode = txt_kodesampah_tambah.getText();
        String kategori = cmb_kategori_edtsampah.getSelectedItem().toString();
        String jenis = txt_jenissampah_edt.getText();
        String deskripsi = txt_deskripsi_edt.getText();
        String harga1Str = txt_hargadhs1_edt.getText();
        String harga2Str = txt_hargadhs2_edt.getText();
        String hargaPengepulStr = txt_hargapgpl_edt.getText();

        // Validasi dasar
        if (kode.isEmpty() || jenis.isEmpty() || deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi semua data yang diperlukan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            double harga1 = Double.parseDouble(harga1Str);
            double harga2 = Double.parseDouble(harga2Str);
            double hargaPengepul = Double.parseDouble(hargaPengepulStr);
            
            Connection conn = com.koneksi.koneksi.konek();
            String sql = "UPDATE sampah SET kategori = ?, jenis = ?, deskripsi = ?, harga1 = ?, harga2 = ?, harga_pengepul = ? WHERE kode_sampah = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kategori);
            pst.setString(2, jenis);
            pst.setString(3, deskripsi);
            pst.setDouble(4, harga1);
            pst.setDouble(5, harga2);
            pst.setDouble(6, hargaPengepul);
            pst.setString(7, kode);
            
            int result = pst.executeUpdate();
            pst.close();
            conn.close();
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data sampah berhasil diperbarui!");
                loadFormEditSampah(kode); 
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diperbarui!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan saat update: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_simpahEditSampahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sampah_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sampah_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sampah_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sampah_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sampah_edit dialog = new Sampah_edit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpahEditSampah;
    private javax.swing.JButton btn_ttpEditsampah;
    private javax.swing.JComboBox<String> cmb_kategori_edtsampah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_deskripsi_edt;
    private javax.swing.JTextField txt_hargadhs1_edt;
    private javax.swing.JTextField txt_hargadhs2_edt;
    private javax.swing.JTextField txt_hargapgpl_edt;
    private javax.swing.JTextField txt_jenissampah_edt;
    private javax.swing.JTextField txt_kodesampah_tambah;
    // End of variables declaration//GEN-END:variables
    
    private void loadFormEditSampah(String kode) {
        txt_kodesampah_tambah.setText(kode); // langsung isi dari parameter

        try (Connection conn = com.koneksi.koneksi.konek()) {
            String sql = "SELECT kategori, jenis, deskripsi, harga1, harga2, harga_pengepul FROM sampah WHERE kode_sampah = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kode);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                cmb_kategori_edtsampah.setSelectedItem(rs.getString("kategori"));
                txt_jenissampah_edt.setText(rs.getString("jenis"));
                txt_deskripsi_edt.setText(rs.getString("deskripsi"));
                txt_hargadhs1_edt.setText(String.valueOf(rs.getDouble("harga1")));
                txt_hargadhs2_edt.setText(String.valueOf(rs.getDouble("harga2")));
                txt_hargapgpl_edt.setText(String.valueOf(rs.getDouble("harga_pengepul")));
            }
            
            rs.close();
            pst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data edit: " + e.getMessage());
        }
    }
    
}
